import { HealthReportRequest } from "./interface";

export const infoTemplate = {
    // error on difference between ajax and got
    // "jrdqtlqk": [],
    "sfymqjczrj": 0,
    "zjdfgj": "",
    "sfyrjjh": "0",
    "cfgj": "",
    "tjgj": "",
    "nrjrq": "0",
    "rjka": "",
    "jnmddsheng": "",
    "jnmddshi": "",
    "jnmddqu": "",
    "jnmddxiangxi": "",
    "rjjtfs": "",
    "rjjtfs1": "",
    "rjjtgjbc": "",
    "jnjtfs": "",
    "jnjtfs1": "",
    "jnjtgjbc": "",
    "sfqrxxss": 1,
    "sfqtyyqjwdg": "0",
    "sffrqjwdg": "0",
    "sfhsjc": "",
    "zgfx14rfh": "0",
    "zgfx14rfhdd": "",
    "sfyxjzxgym": "1",
    "sfbyjzrq": "5",
    "jzxgymqk": "2",
    "tw": "0",
    "sfcxtz": "0",
    "sfjcbh": "0",
    "sfcxzysx": "0",
    "qksm": "",
    "sfyyjc": "0",
    "jcjgqr": "0",
    "remark": "",
    "sfzx": "0",
    "sfjcwhry": "0",
    "sfjchbry": "0",
    "sfcyglq": "0",
    "gllx": "",
    "glksrq": "",
    "jcbhlx": "",
    "jcbhrq": "",
    "bztcyy": "",
    "sftjhb": "0",
    "sftjwh": "0",
    "sfjcqz": "",
    "jcqzrq": "",
    "jrsfqzys": "",
    "jrsfqzfy": "",
    "sfyqjzgc": "0",
    "sfsqhzjkk": "1",
    "sqhzjkkys": "1",
    "gwszgzcs": "",
    "szgj": "",
    "fxyy": "",
    "jcjg": "",
    "gwszdd": "",
    "szsqsfybl": 0,
    "sfygtjzzfj": "0",
    "gtjzzfjsj": "",
    "szgjcs": "",
    "ismoved": 0
} as HealthReportRequest;
